### ISSUE TITLE
Proposal to add my own open-source 'Rotary Inverted Pendulum' / 'Furuta Pendulum'

### ISSUE THREAD

**Issue by ferrolho** [stephane-caron/awesome-open-source-robots#16]
Hi, Stéphane! 😃 Here is a proposal to add my open-source rotary inverted pendulum. Not sure if most would call it a robot, but it can do a fair bit of robot stuff. It's particularly interesting for studying optimal control and reinforcement learning applied to a naturally unstable (and chaotic) system. 🤖

* [x] I have checked that the build is open ([guidelines](https://github.com/tasts-robots/us/blob/main/CONTRIBUTING.md))
* [x] I have checked that the software to control the robot is open ([guidelines](https://github.com/tasts-robots/us/blob/main/CONTRIBUTING.md))

Relevant information about the robot:

* Type: Other? I don't think it fits any of the existing categories.
* License: MIT license
* Build instructions: https://github.com/ferrolho/rotary-inverted-pendulum
* Model: no URDF model yet, but CAD is publicly available in the [Onshape project](https://www.onshape.com/en/), and STL meshes are available [here](https://github.com/ferrolho/rotary-inverted-pendulum/blob/main/meshes).
* Software: https://github.com/ferrolho/rotary-inverted-pendulum

Icing on the cake, here is a picture for the gallery:

![image](https://github.com/user-attachments/assets/d9f767d7-f4c9-41c2-bc05-2bb2bf8ea4e3)

Robotically,
Henrique Ferrolho

**Comment by stephane-caron** [comment]
Awesome! Thanks Henrique for linking this very nice project :smiley: 

I created an Educational section similar to the one in [Awesome Robot Descriptions](https://github.com/robot-descriptions/awesome-robot-descriptions). Don't hesitate to open a PR there when there is a URDF description for the pendulum as well :+1:

**Comment by ferrolho** [comment]
Thanks for accepting the project. I will definitely open a PR on the other repo to add the description once it is ready.

So far, I have manufactured three working pendulums, but there are more in the "assembly line"! 

![image](https://github.com/user-attachments/assets/72746674-af1a-4226-ad9f-16d4cd7b477a)

I am quite happy with the design, mechanics, and electronics for now; so the next steps will most likely focus on software — @VladimirIvan has already been adding [some goodness](https://github.com/ferrolho/rotary-inverted-pendulum/pull/1) on that front.
