### ISSUE TITLE
WheelBot picture for the gallery?

### ISSUE THREAD

**Issue by stephane-caron** [stephane-caron/awesome-open-source-robots#3]
@AndReGeist thank you for making the WheelBot an open source robot, it is awesome :smiley: 

There aren't pictures in the github repo. Can include those from the [project's website](https://sites.google.com/view/wheelbot) in the [gallery](https://github.com/tasts-robots/awesome-open-source-robots#gallery)? If you'd like let's add a picture there too.

**Comment by AndReGeist** [comment]
@stephane-caron thank you for the kind words! It would be nice, if you could add fotos from the [project's website](https://sites.google.com/view/wheelbot) to your [gallery](https://github.com/tasts-robots/awesome-open-source-robots#gallery). Also checkout  the [open robot iniative](https://open-dynamic-robot-initiative.github.io/) from my former colleagues at the MPI-IS, the documentation of their different robot builds is awe inspiring.

**Comment by stephane-caron** [comment]
Thank you :smiley: I have updated the gallery and added the ODRI projects to the list.
