### ISSUE TITLE
Adding "open robot iniative"

### ISSUE THREAD

**Issue by AndReGeist** [stephane-caron/awesome-open-source-robots#5]
Hi there! Here is a proposal to add the open source robot [open robot initiative](https://open-dynamic-robot-initiative.github.io/) by @fgrimminger et al. 🤖

* [x] I have checked that the [build is open](https://github.com/tasts-robots/us/blob/main/CONTRIBUTING.md)
* [x] I have checked that the [software to control the robot is open](https://github.com/tasts-robots/us/blob/main/CONTRIBUTING.md)

Here is some information about the robot:

* Type: Quadruped, Biped
* License: CC0-1.0 license
* Build instructions: https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware
* Model: https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware
* Software: https://github.com/orgs/open-dynamic-robot-initiative/repositories?type=all

Icing on the cake, here is a picture for the gallery:
<img width="834" alt="open robot iniative_overview" src="https://user-images.githubusercontent.com/11872530/235352942-62106e6a-bf22-47fd-addf-dabd505294a2.png">

Robotically,
A. René Geist

**Comment by stephane-caron** [comment]
Done. Great initiative :smiley:
